org: kizza
app: nextjs
service: frontend

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  stackName: ${self:app}-${self:service}-${self:provider.stage}

plugins:
  - serverless-lift

# stages: Use stages when using version 4
custom:
  dev:
    params:
      domain:
        - staging.com

  prod:
    params:
      domain:
        - production.com

constructs:
  landing:
    type: static-website
    path: out
    # domain: ${self:custom.${self:provider.stage}.params.domain}
    # certificate: arn:aws:acm:us-east-1:account:certificate/
    extensions:
      bucket:
        Properties:
          PublicAccessBlockConfiguration:
            BlockPublicPolicy: false
