org: kizza
app: kenmore-vocal-studio
service: frontend

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  stackName: ${self:app}-${self:service}-${self:provider.stage}

plugins:
  - serverless-lift

# stages: Use stages when using version 4
custom:
  dev:
    params:
      domain:
        - dev.kenmorevocalstudio.com

  prod:
    params:
      domain:
        - kenmorevocalstudio.com
        - www.kenmorevocalstudio.com

constructs:
  landing:
    type: static-website
    path: out
    redirectToMainDomain: true
    domain: ${self:custom.${self:provider.stage}.params.domain}
    certificate: arn:aws:acm:us-east-1:373532833815:certificate/0211973f-fab5-4d91-b7a2-3da3658f0f31

resources:
  # Use stackName for automatic outputs (to avoid ${service-stage} clash with other app exports)
  Outputs:
    ServerlessDeploymentBucketName:
      Export:
        Name: ${self:provider.stackName}-ServerlessDeploymentBucketName
